### ISSUE TITLE
Newest Spigot

### ISSUE THREAD

**Issue by leventinio** [brunyman/EconomyBank#4]
[10:35:53] [Server thread/INFO]: Der_Fuchs issued server command: /bank
[10:35:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'bank' in plugin MysqlEconomyBank v1.10.1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1600.jar:git-Spigot-4bd94dc-f4ca180]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by brunyman** [comment]
you get the error because the plugin is disabled, make sure you have installed an economy plugin and vault, check the dependency info on the plugin description: https://www.spigotmc.org/resources/economy-bank.7674/  for more info please post the plugin loading messages, it will tell you what's wrong
