### ISSUE TITLE
Exception while checking a player's balance

### ISSUE THREAD

**Issue by Artuto** [brunyman/EconomyBank#5]
Hi, I'm using 1.12.0 in Paper 1.13.2 and when I do `/bank balance player` an exception is thrown:

```[15:02:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bank' in plugin MysqlEconomyBank v1.12.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-458]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-458]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at net.craftersland.money.database.MoneyMysqlInterface.hasAccount(MoneyMysqlInterface.java:29) ~[?:?]
        at net.craftersland.money.ConfigHandler.printMessage(ConfigHandler.java:122) ~[?:?]
        at net.craftersland.money.commands.BalanceCmd.runAdminCmd(BalanceCmd.java:91) ~[?:?]
        at net.craftersland.money.CommandHandler.onCommand(CommandHandler.java:58) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-458]
        ... 15 more
```

**Comment by Artuto** [comment]
Its been 89 years...

**Comment by brunyman** [comment]
Should be fixed in 1.16.0 version, can you confirm?
