### ISSUE TITLE
Internal Error when checking/set offline players's Balance ( UUID or Name ) ingame.

### ISSUE THREAD

**Issue by Talithaald** [brunyman/EconomyBank#7]
When we check through Console, it works perfectly. Offline nor Online players.
note that "AdamTest" is not connected.

input & output:

sent from Console:
`
> bank Balance AdamTest
[09:10:49] [Server thread/INFO]: >> AdamTest balance: 0.0
`

sent from Ingame:
`
[09:10:55] [Server thread/INFO]: Adam issued server command: /bank balance AdamTest
[09:10:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bank' in plugin MysqlEconomyBank v1.15.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[Paper.jar:git-Paper-655]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[Paper.jar:git-Paper-655]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[Paper.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[Paper.jar:git-Paper-655]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.craftersland.money.database.MoneyFlatFileInterface.hasAccount(MoneyFlatFileInterface.java:24) ~[?:?]
	at net.craftersland.money.ConfigHandler.printMessage(ConfigHandler.java:124) ~[?:?]
	at net.craftersland.money.commands.BalanceCmd.runAdminCmd(BalanceCmd.java:96) ~[?:?]
	at net.craftersland.money.CommandHandler.onCommand(CommandHandler.java:58) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper.jar:git-Paper-655]
	... 15 more
`

**Comment by brunyman** [comment]
I can't reproduce this, can you please send a full server log?

Thanks

**Comment by Talithaald** [comment]
sure thing.

the point is, when we check player's balance through console it will NOT give any errors.
The error will appear if we execute the command in-game ( as a player ).

I will post pics about the differences when executing commands in-game and through console;

Console execution:
![image](https://user-images.githubusercontent.com/19772382/86374887-41f38b00-bcaf-11ea-9f2e-86a9e94d663b.png)

In-game execution:
![image](https://user-images.githubusercontent.com/19772382/86376173-cd215080-bcb0-11ea-8465-c0e8529672c2.png)

copied from logs.txt
![image](https://user-images.githubusercontent.com/19772382/86376286-fa6dfe80-bcb0-11ea-9c44-322c234b9732.png)

**Comment by brunyman** [comment]
Hi, do you still get this error in version 1.16.0?

Thanks!
